### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by vikmeup**
In order to support this, you guys need to create release with `LinkKit.zip` name

Here is information: https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

### CODE REVIEW

**Comment by afh** [comment]
Thanks for the initiative @vikmeup, we're working on getting Carthage support integrated.

**Comment by vikmeup** [comment]
@afh any ETA?

Also some useful resources:

That's how Instabug configured: 
`https://github.com/Instabug/Instabug-iOS/blob/master/Carthage.json`

in Cartfile you specify:
`binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Carthage.json"`

**Comment by afh** [comment]
@vikmeup Thanks for providing additional resources. I expect Carthage support to be integrated into the Plaid Link iOS release workflow next week.

**Comment by afh** [comment]
@vikmeup Have a look at #166 and give it a try; I'm closing this PR in favor it.

**Pull request closed without merging**
